name: Example workflow for S3 Deploy
on: 
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESSKEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRETKEY }}
        aws-region: ca-central-1
        
    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync . s3://ramgopalsrikark.online
        
    - name: invalidating cloudfront actions
      run: |
        aws cloudfront create-invalidation --distribution-id E1W00BQM05A1P5 --paths /*
  

  
