# This is a basic workflow to help you get started with Actions

name: S3 deploy workflow

on:
  push:
    branches: [ master ]

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID : ${{ secrets.AWS_ACCESSKEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRETKEY }}
    steps:
        - uses: actions/checkout@v2
        - name: Install dependencies
          run: yarn
          
        - name: Build
          run: yarn build
        
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.S3_BUCKET_REGION }}
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: true
            no-cache: true
